### PR TITLE
chore(prettier): run prettier on the code

### PR DESCRIPTION
**Pull request by benlesh**
- runs [prettier](https://github.com/jlongster/prettier) on the code
- adds a script item `npm run prettier`, that we should probably run before each commit, really.

### CODE REVIEW

**Comment by blesh** [comment]
ACK! Double quotes! Why @jlongster? haha.

**Comment by blesh** [comment]
Fixed... single quotes 😅 that was close..

**Comment by blesh** [comment]
cc @lrowe ... huh? huh? yes? no?

**Comment by lrowe** [comment]
I'm totally for this long term but we should hold fire on converting an existing project until prettier has stabilized a little further.

**Comment by benlesh** [comment]
Just going through my open PRs and closing ones that don't make sense to leave open.

**Pull request closed without merging**
